name: fabrica_do_multiverso
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  cloud_firestore: ^4.3.1
  firebase_auth: ^4.2.5
  firebase_core: ^2.4.1
  numberpicker: ^2.0.1
  flutter:
    sdk: flutter
  http: ^0.13.5
  path_provider: ^2.0.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # assets:     
  #   - assets\fonts

  fonts:
    - family: Anton
      fonts:
      - asset: assets/fonts/Anton-Regular.ttf

