// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpvv-TVBMV3plxqer4YoPWKJ2y3M15734',
    appId: '1:692522208889:web:1341c14489b70cb9668ea8',
    messagingSenderId: '692522208889',
    projectId: 'fabrica-do-multiverso',
    authDomain: 'fabrica-do-multiverso.firebaseapp.com',
    storageBucket: 'fabrica-do-multiverso.appspot.com',
    measurementId: 'G-28MW5SR3TN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTITqQVSsHFbP0cmytvo5JibNm03dR4t0',
    appId: '1:692522208889:android:fa1b71c1c2bec5ab668ea8',
    messagingSenderId: '692522208889',
    projectId: 'fabrica-do-multiverso',
    storageBucket: 'fabrica-do-multiverso.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBz4CDOGCWP_iZOGrXx84ysU0t9I0ggq0I',
    appId: '1:692522208889:ios:4682264436526d7a668ea8',
    messagingSenderId: '692522208889',
    projectId: 'fabrica-do-multiverso',
    storageBucket: 'fabrica-do-multiverso.appspot.com',
    iosClientId: '692522208889-hnsjlkjmsu7b94t5eorcgdgfrdjt4pkm.apps.googleusercontent.com',
    iosBundleId: 'com.example.fabricaDoMultiverso',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBz4CDOGCWP_iZOGrXx84ysU0t9I0ggq0I',
    appId: '1:692522208889:ios:4682264436526d7a668ea8',
    messagingSenderId: '692522208889',
    projectId: 'fabrica-do-multiverso',
    storageBucket: 'fabrica-do-multiverso.appspot.com',
    iosClientId: '692522208889-hnsjlkjmsu7b94t5eorcgdgfrdjt4pkm.apps.googleusercontent.com',
    iosBundleId: 'com.example.fabricaDoMultiverso',
  );
}
